# Generated by Django 4.1.2 on 2023-02-15 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='', max_length=400)),
                ('tel', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('eid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField(default=None)),
                ('position', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='', max_length=1)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('net', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='', upload_to='static/products/')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdate', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(default='', max_length=35)),
                ('bank', models.CharField(default='', max_length=50)),
                ('bill', models.ImageField(default='', upload_to='static/bills/')),
                ('comment', models.CharField(default='', max_length=200)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateTimeField(auto_now_add=True)),
                ('company', models.CharField(default='', max_length=50)),
                ('tag', models.CharField(default='', max_length=50)),
                ('comment', models.CharField(default='', max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.employees')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Samplesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesale', models.DateField(default=None)),
                ('amount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Reject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='', max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.employees')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oprice', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.orders')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Confirms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.employees')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='', max_length=200)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Accepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.employees')),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shoppingapp.orders')),
            ],
        ),
    ]
